MyWeb/MyWeb/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic.base import TemplateView

handler404 = "corm.views.NotFound.error_404"

urlpatterns = [
    path("admin/", admin.site.urls),
    path('myApp/', include('myApp.urls')),
    path('corm/', include('corm.urls')),
    path('gplot/', include('gplot.urls')),
    path('mychart/', include('mychart.urls')),
    path('myDatable/', include('myDatable.urls')),
    path('api/', include('api.urls')),

    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

MyWeb/api/urls.py
from django.urls import include, path

from .views import MyTokenObtainPairView, getUserAccess, chatroom

from rest_framework_simplejwt.views import (
    TokenRefreshView,
)

urlpatterns = [
    path("token/", MyTokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("useraccess/", getUserAccess, name="getUserAccess"),
    path("chatroom/<str:room_name>/", chatroom, name="chatroom"),
]

MyWeb/mydtmx/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from . import views

urlpatterns = [
    path(
        "movie_dt_server",
        TemplateView.as_view(template_name="mydtmx/movie_dt_server.html"),
        name="movie_dt_server",
    ),
    # path("movie_data/", views.MovieistView.as_view()),
    path("movie_data/", views.movie_dt_ajax_data, name="movie_data"),
    path("movie_dt_client", views.movie_datatable, name="movie_dt_client"),
    path("", views.index),
    path("movies", views.movie_list, name="movie_list"),
    path("movies/add", views.add_movie, name="add_movie"),
    path("movies/remove/<int:pk>", views.remove_movie, name="remove_movie"),
    path("movies/edit/<int:pk>", views.edit_movie, name="edit_movie"),
    path("movies/edit/addrow", views.edit_movie_addcomment, name="create-row-comment"),
    path("movie_year", views.movie_year, name="movie_year"),
    path("movie_title", views.movie_title, name="movie_title"),
]

MyWeb/mydtmx/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Movie(models.Model):

    title = models.CharField(max_length=40, unique=True)

    year = models.PositiveSmallIntegerField(
        validators=[
            MinValueValidator(1995),
            MaxValueValidator(2050),
        ]
    )

    rating = models.PositiveSmallIntegerField(
        choices=(
            (1, "★☆☆☆☆"),
            (2, "★★☆☆☆"),
            (3, "★★★☆☆"),
            (4, "★★★★☆"),
            (5, "★★★★★"),
        )
    )

MyWeb/mydtmx/forms.py
from django import forms

from .models import Movie


class MovieForm(forms.ModelForm):

    class Meta:
        model = Movie
        # fields = ["title", "year", "rating"]
        fields = ["title", "year"]

MyWeb/mydtmx/views.py
import json

from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404

# """ from django.core import serializers """" ## directly using Django Serilizer
from rest_framework import serializers

from .models import Movie
from .forms import MovieForm
import time

# from django_serverside_datatable.views import ServerSideDatatableView


# class MovieistView(ServerSideDatatableView):
#     queryset = Movie.objects.all()
#     columns = ["id", "title", "year", "rating"]


class MyModelSerializer(serializers.ModelSerializer):
    class Meta:
        model = Movie
        fields = "__all__"


def movie_datatable(request):
    data = Movie.objects.all().values()
    json_data = json.dumps(list(data))
    print(json_data)
    context = {"table_data": json_data}
    return render(request, "mydtmx/movie_dt_client.html", context)
    ## using Django serlizer
    # data = serializers.serialize("json", Movie.objects.all())

    # data = MyModelSerializer(Movie.objects.all(), many=True).data
    return JsonResponse(data, safe=False)
    # return HttpResponse(data, content_type="application/json")


def movie_dt_ajax_data(request):

    ##  get draw sequence from client, for serverside = True
    draw = 1
    for key, value in request.GET.items():
        try:
            key_dict = json.loads(key)
            draw_input = key_dict["draw"]
            if draw_input is not None:
                draw = int(draw_input)
                break
        except Exception:
            print(f"There is no draw in the input key, {key} ")
    # for serverside = True
    print(f"movie_dt_ajax_data ... {request.GET}, {draw}")

    data = Movie.objects.all().values()
    ret = {
        "draw": draw,
        "recordsTotal": len(data),
        "recordsFiltered": len(data),
        "data": list(data),
    }
    print(ret)
    return HttpResponse(json.dumps(ret), content_type="application/json")


def index(request):
    print("Movie  index.html ...")
    return render(request, "mydtmx/index.html")


def movie_list(request):
    print("Movie_list ...to movie_list.html")
    # time.sleep(5)
    return render(
        request,
        "mydtmx/movie_list.html",
        {
            "movies": Movie.objects.all(),
        },
    )


def add_movie(request):
    print("add_movie ....")
    if request.method == "POST":
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return HttpResponse(
                status=204,
                headers={
                    "HX-Trigger": json.dumps(
                        {
                            "movieListChanged": None,
                            "showMessage": f"{movie.title} added.",
                        }
                    )
                },
            )
    else:
        form = MovieForm()
    return render(
        request,
        "mydtmx/movie_form.html",
        {
            "form": form,
        },
    )


def edit_movie_addcomment(request):
    print("GET edit_movie_addcomment")
    if request.method == "GET":
        return render(request, "mydtmx/partialform.html")


def edit_movie(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    if request.method == "POST":
        print(f"edit_movie {request.POST}")
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            form.save()
            return HttpResponse(
                status=204,
                headers={
                    "HX-Trigger": json.dumps(
                        {
                            "movieListChanged": None,
                            "showMessage": f"{movie.title} updated.",
                        }
                    )
                },
            )
    else:
        form = MovieForm(instance=movie)

    print("edit_movie send to movie_form.html")
    return render(
        request,
        "mydtmx/movie_form.html",
        {
            "form": form,
            "movie": movie,
        },
    )


@require_POST
def remove_movie(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    movie.delete()
    return HttpResponse(
        status=204,
        headers={
            "HX-Trigger": json.dumps(
                {"movieListChanged": None, "showMessage": f"{movie.title} deleted."}
            )
        },
    )


def movie_year(request):
    print("movie_year ...to movie_selection.html")

    return render(
        request,
        "mydtmx/movie_selection.html",
        {
            "movie_years": Movie.objects.all(),
        },
    )


def movie_title(request):
    year = request.GET.get("year")
    print(f"movie_title ...for {year} to movie_selection.html")
    movies = Movie.objects.filter(year=year)
    return render(request, "mydtmx/movie_list.html", {"movies": movies})

MyWeb/templates/mydtmx/index.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Movie List with Bootstrap5/HTMX/Modal
{% endblock %}

{% block style%}
<script src="https://unpkg.com/htmx.org@1.6.1/dist/htmx.min.js"></script>
{% endblock %}


{% block content %}
<div class="container">
  <div class="px-5 my-5 text-center">
    <h1>My Movie Collection</h1>
  </div>
  <button hx-get="{% url 'add_movie' %}" hx-target="#dialog" class="btn btn-primary">
    Add a movie
  </button>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Year</th>
        <th>Rating</th>

      </tr>
    </thead>
    <tbody hx-trigger="load, movieListChanged from:body" hx-get="{% url 'movie_list' %}" hx-target="this">
      <tr>
        <td class="spinner-border" role="status">
          <span class="visually-hidden">Loading...</span>
        </td>
      </tr>
    </tbody>
  </table>

</div>

<!-- Placeholder for the modal -->
<div id="modal" class="modal fade">
  <div id="dialog" class="modal-dialog" hx-target="this"></div>
</div>

<!-- Empty toast to show the message -->
<div class="p-3" style="position: fixed; top: 0; right:0;">
  <div id="toast" class="toast align-items-center text-white bg-success border-0">
    <div class="d-flex">
      <div id="toast-body" class="toast-body"></div>
      <button type="button" class="close m-2" data-dismiss="toast" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
</div>


<script src="{% static 'js/dialog.js' %}"></script>


{% endblock %}

MyWeb/templates/mydtmx/movie_dt_client.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Movie Collection Datatable
{% endblock %}

{% block style%}

<link href="https://cdn.datatables.net/v/bs4/dt-1.13.3/datatables.min.css" rel="stylesheet" />

<script src="https://cdn.datatables.net/v/bs4/dt-1.13.3/datatables.min.js"></script>

<script src="https://unpkg.com/htmx.org@1.6.1/dist/htmx.min.js"></script>

{% endblock %}



{% block content %}


<div class="container">
    <div class="px-5 my-5 text-center">
        <h1>My Movie Collection</h1>
    </div>
    <button hx-get="{% url 'add_movie' %}" hx-target="#dialog" class="btn btn-primary">
        Add a movie
    </button>

    <div class="card">
        <div class="card-body">
            <table id="data-grid" class="table table-sriped table-bordered">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Year</th>
                        <th>Rating</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody></tbody>
                <tfoot></tfoot>
            </table>
        </div>
    </div>

</div>

<!-- Placeholder for the modal -->
<div id="modal" class="modal fade">
    <div id="dialog" class="modal-dialog" hx-target="this"></div>
</div>

<!-- Empty toast to show the message -->
<div class="p-3" style="position: fixed; top: 0; right:0;">
    <div id="toast" class="toast align-items-center text-white bg-success border-0">
        <div class="d-flex">
            <div id="toast-body" class="toast-body"></div>
            <button type="button" class="close m-2" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
</div>
<!-- My javascript for this page to handle datatable -->
<script>
    var dataset = {{ table_data | safe}}
    console.log(dataset)


    var movieTable = $('#data-grid').DataTable({
        data: dataset,
        columns: [
            {
                data: "title",
            },
            {
                data: "year",
            },
            {
                data: "rating",
            },
            {
                data: "id",
                render: function (data, type, row) {
                    return "<button class='btn btn-primary' hx-get='/mydtmx/movies/edit/" + row.id + "' hx-target='#dialog' title='Update'>Edit</button>"
                }
            }
        ],
        // Use DataTables' initComplete callback to tell htmx to reprocess any htmx attributes in the table
        // DataTables docs: https://datatables.net/reference/option/initComplete
        // htmx docs: https://htmx.org/api/#process AND https://htmx.org/docs/#3rd-party
        initComplete: function (settings, json) {

        },
    });
    ///  end of  DataTable function


</script>

<script src="{% static 'js/modalog.js' %}"></script>



{% endblock %}

MyWeb/templates/mydtmx/movie_dt_server.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Movie Collection Datatable
{% endblock %}

{% block style%}
<link href="https://cdn.datatables.net/v/bs4/dt-2.0.8/datatables.min.css" rel="stylesheet">

<script src="https://cdn.datatables.net/v/bs4/dt-2.0.8/datatables.min.js"></script>
<!--
<link href="https://cdn.datatables.net/v/bs4/dt-1.13.3/datatables.min.css" rel="stylesheet" />

<script src="https://cdn.datatables.net/v/bs4/dt-1.13.3/datatables.min.js"></script>
-->

<script src="https://unpkg.com/htmx.org@1.6.1/dist/htmx.min.js"></script>

{% endblock %}

<!--

https://jacklinke-1666476519144.hashnode.dev/using-htmx-and-server-side-datatables-net-together-in-a-django-project

https://pypi.org/project/djangorestframework-datatables/

-->

{% block content %}


<div class="container">
    <div class="px-5 my-5 text-center">
        <h1>My Movie Collection</h1>
    </div>
    <button hx-get="{% url 'add_movie' %}" hx-target="#dialog" class="btn btn-primary">
        Add a movie
    </button>

    <div class="card">
        <div class="card-body">
            <table id="movieTable" class="table table-sriped table-bordered">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Year</th>
                        <th>Rating</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody></tbody>
                <tfoot></tfoot>
            </table>
        </div>
    </div>

</div>

<!-- Placeholder for the modal -->
<div id="modal" class="modal fade">
    <div id="dialog" class="modal-dialog" hx-target="this"></div>
</div>

<!-- Empty toast to show the message -->
<div class="p-3" style="position: fixed; top: 0; right:0;">
    <div id="toast" class="toast align-items-center text-white bg-success border-0">
        <div class="d-flex">
            <div id="toast-body" class="toast-body"></div>
            <button type="button" class="close m-2" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
</div>
<!-- My javascript for this page to handle datatable -->
<script>
    $(document).ready(function () {
        var movieTable = $('#movieTable').DataTable({
            processing: true,
            serverSide: false,
            ajax: {
                url: "{% url 'movie_data' %}?region='APAC'",
                contentType: "application/json",
                data: function (d) {
                    return JSON.stringify(d);
                }
            },
            lengthMenu: [3, 5, 10, { label: 'All', value: -1 }],
            columns: [
                {
                    data: "title",
                },
                {
                    data: "year",
                },
                {
                    data: "rating",
                },
                {
                    data: "id",
                    render: function (data, type, row) {
                        return "<button class='btn btn-primary' hx-get='/mydtmx/movies/edit/" + row.id + "' hx-target='#dialog' title='Update'>Edit</button>"
                    }
                }
            ],
            // Use DataTables' initComplete callback to tell htmx to reprocess any htmx attributes in the table
            // DataTables docs: https://datatables.net/reference/option/initComplete
            // htmx docs: https://htmx.org/api/#process AND https://htmx.org/docs/#3rd-party
            initComplete: function (settings, json) {
                htmx.process('#movieTable');

            },
        });
        ///  end of  DataTable function

        // Add an event listener that updates the table whenever an htmx request completes
        // DataTables docs: https://datatables.net/reference/api/ajax.reload()
        // htmx docs: https://htmx.org/events/#htmx:afterRequest
        document.body.addEventListener('htmx:afterRequest', function (evt) {
            console.log("html htmx:afterRequest", evt);
            if (evt.target.tagName != "BUTTON") {
                movieTable.ajax.reload(function () {
                    htmx.process('#movieTable');
                }, false)
            }
        });
    });


</script>

<script src="{% static 'js/modalog.js' %}"></script>



{% endblock %}

MyWeb/templates/mydtmx/movie_form.html
{% load widget_tweaks %}
{% with WIDGET_ERROR_CLASS='is-invalid' %}
<form hx-post="{{ request.path }}" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' class="modal-content">
  <div class="modal-header">
    <h5 class="modal-title">Edit Movie</h5>
    <button type="button" class="close" data-dismiss="modal">&times;</button>
  </div>
  <div class="modal-body">
    <div class="form-group">
      <label for="{{ form.title.id_for_label }}">Title</label>
      {% render_field form.title class="form-control" placeholder="Back to the Future II" %}
      <div class="invalid-feedback">{{ form.title.errors|first }}</div>
    </div>
    <div class="form-group">
      <label for="{{ form.year.id_for_label }}">Year</label>
      {% render_field form.year class="form-control" placeholder="1980" %}
      <div class="invalid-feedback">{{ form.year.errors|first }}</div>
    </div>

    <div id="partial-form">
    </div>

  </div>
  <div class="modal-footer">
    {% if movie %}
    <button type="button" class="btn btn-danger" hx-post="{% url 'remove_movie' pk=movie.pk %}">Remove</button>
    <span class="flex-grow-1"></span>

    <button type="button" class="btn btn-success" type="submit" hx-get="{% url 'create-row-comment' %}"
      hx-target="#partial-form" hx-swap="beforeend">+ Add Row</button>

    {% endif %}
    <button type="button" class="btn btn-secondary" data-dismiss="modal">
      Cancel
    </button>
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
</form>
{% endwith %}

MyWeb/templates/mydtmx/movie_list.html
{% for movie in movies %}
<tr id="movie-{{ movie.pk }}" class="movie-row">
  <td>{{ movie.title }}</td>
  <td>{{ movie.year }}</td>
  <!--
  <td>{{ movie.get_rating_display }}</td>
  -->
  <td>
    <button class="btn btn-primary btn-sm" hx-get="{% url 'edit_movie' pk=movie.pk %}" hx-target="#dialog">Edit</button>
  </td>
</tr>
{% endfor %}

MyWeb/templates/mydtmx/movie_selection.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Movie List with Bootstrap4/HTMX/Modal
{% endblock %}

{% block style%}
<script src="https://unpkg.com/htmx.org@1.6.1/dist/htmx.min.js"></script>
{% endblock %}


{% block content %}
<div class="container">
    <div class="px-5 my-5 text-center">
        <h1>My Movie selection</h1>
    </div>
    <div>
        <select name="year" hx-get="{% url 'movie_title' %}" hx-trigger="change" hx-target="#id_movies">
            {% for m in movie_years %}
            <option value="{{ m.year}}">{{ m.year}}</option>
            {% endfor %}
        </select>
    </div>
    <div id="id_movies">
    </div>

    {% endblock %}

MyWeb/templates/mydtmx/partialform.html
<form hx-target="this" hx-swap="innerHTML">
    <div class="row">
        <label for="comment"> Comment</label>
        <input name="comment" type="text"></input>
        <button type="button" class="btn btn-danger" hx-on="click: this.closest('form').remove()">remove</button>
    </div>
</form>