MyWeb/MyWeb/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic.base import TemplateView

handler404 = "corm.views.NotFound.error_404"

urlpatterns = [
    path("admin/", admin.site.urls),
    path('myApp/', include('myApp.urls')),
    path('corm/', include('corm.urls')),
    path('gplot/', include('gplot.urls')),
    path('mychart/', include('mychart.urls')),
    path('myDatable/', include('myDatable.urls')),
    path('api/', include('api.urls')),

    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

MyWeb/api/urls.py
from django.urls import include, path

from .views import MyTokenObtainPairView, getUserAccess, chatroom

from rest_framework_simplejwt.views import (
    TokenRefreshView,
)

urlpatterns = [
    path("token/", MyTokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("useraccess/", getUserAccess, name="getUserAccess"),
    path("chatroom/<str:room_name>/", chatroom, name="chatroom"),
]

MyWeb/myApp/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.PersonListView.as_view(), name='person_changelist'),
    path('add/', views.PersonCreateView.as_view(), name='person_add'),
    path('<int:pk>/', views.PersonUpdateView.as_view(), name='person_change'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),

    path('dropdown/', views.example_dropdown, name='example_dropdown'),

    path('get_cities_ajax/', views.get_cities_ajax,     name='get_cities_ajax'),

    path('basic_contact/', views.basic_contact,     name='basic_contact'),

    path('search_user/', views.search_user, name='search_user'),
    path('search_car/', views.search_car, name='search_car'),
    path('download_file/', views.download_file, name='download_file'),

    path('group_user/', views.group_user, name='group_user'),

]

MyWeb/myApp/models.py
from django.db import models
from .choices import CAR_BRAND_CHOICES, CAR_TANSMISSION_TYPE

from . import Util


class Car(models.Model):
    vin = models.IntegerField(unique=True)

    brand = models.CharField(max_length=200, choices=CAR_BRAND_CHOICES)
    # brand = models.CharField(max_length=200, choices=Util.getDBChoice(
    #     'select distinct brand from myApp_car', 'Car_Brand'))

    trans_type = models.CharField(
        max_length=200, choices=CAR_TANSMISSION_TYPE, verbose_name="TransmissionType", )

    mileage = models.IntegerField(default=0)
    color = models.CharField(max_length=200,)
    year = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.vin)


class Country(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Person(models.Model):
    name = models.CharField(max_length=100)
    birthdate = models.DateField(null=True, blank=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

MyWeb/myApp/forms.py
from django import forms

from .models import Person, City, Car

from . import Util


# class CarListingForm(forms.ModelForm):
#     brand = forms.ChoiceField(choices=Util.getDBChoice(
#         'select distinct brand from myApp_car', 'Car_Brand'))

#     class Meta:
#         model = Car
#         exclude = ['brand']


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ('name', 'birthdate', 'country', 'city')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['city'].queryset = City.objects.filter(
                    country_id=country_id).order_by('name')

            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by(
                'name')


class ContactForm(forms.Form):
    name = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'style': 'border-color: blue;',
                'id': 'my-id'
            }
        ),
        help_text='Help_text:  Form.name'
    )
    email = forms.EmailField(
        max_length=254,
        widget=forms.TextInput(attrs={'style': 'border-color: green;'})
    )

    password = forms.CharField(widget=forms.PasswordInput())

    message = forms.CharField(
        max_length=2000,
        widget=forms.Textarea(attrs={'style': 'border-color: orange;'}),
        help_text='Help_text:  Write here your message!',
        required=False
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            attrs = {
                "placeholder": f'Place holder {str(field)}',
                "class": 'form-control'
            }

            self.fields[str(field)].widget.attrs.update(attrs)

    def clean(self):
        cleaned_data = super(ContactForm, self).clean()
        name = cleaned_data.get('name')

        email = cleaned_data.get('email')
        message = cleaned_data.get('message')
        if not name and not email and not message:
            raise forms.ValidationError('You have to write something!')
        else:
            print("pass clean")

    def clean_password(self, *args, **kwargs):
        passwd = self.cleaned_data.get("password")
        if passwd == '12345':
            print("rase validate error for password")
            raise forms.ValidationError("Password can't be 12345")
        return passwd

MyWeb/myApp/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.http import JsonResponse, HttpResponse
from django.contrib import messages
import time
import os
import json

from collections import namedtuple

from .Util import getPropertiesList, getPropertiesJSONData
from .models import Person, City, Car
from .forms import PersonForm, ContactForm
from .domainobj import DropDownKeyValue

from .filters import UserFilter, CarListingFilter

import logging

logger = logging.getLogger(__name__)


def example_dropdown(request):
    # subject = namedtuple("subject", "id title")
    # subject = namedtuple("subject", ["key", "value"])
    # subjects = [subject(1, 'CANADA'), subject(2, 'US')]

    subjects = getPropertiesList('country')

    context = {'subjects': subjects}

    return render(request, 'myApp/dropdown.html', context)


class PersonListView(ListView):
    model = Person
    context_object_name = 'people'


class PersonCreateView(CreateView):
    model = Person
    form_class = PersonForm
    success_url = reverse_lazy('myApp/person_changelist')


class PersonUpdateView(UpdateView):
    model = Person
    form_class = PersonForm
    success_url = reverse_lazy('myApp/person_changelist')


def load_cities(request):
    country_id = request.GET.get('countryId')
    cities = None
    if country_id != '':
        cities = City.objects.filter(country_id=country_id).order_by('name')

    return render(request, 'myApp/city_dropdown_list_options.html', {'cities': cities})


def get_cities_ajax(request):
    subject_id = request.GET.get(
        'subject_id') or request.POST.get('subject_id')
    cities = getPropertiesJSONData(subject_id)
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)
    return JsonResponse(cities, safe=False)


def basic_contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)

        print(form.data['name'] + " / " + form['password'].value())

        if form.is_valid():
            print(
                "after form validate, form.cleaned_data['password'] " + " /  " + form.instance.message)
        else:
            print(form.errors)
    else:
        form = ContactForm()
        # this won't take effect,
        form.data['name'] = "peter"
    return render(request, 'myApp/basic_contact.html', {'form': form})


def search_user(request):
    user_list = User.objects.all()
    download_file = 'N'
    if request.method == 'POST':
        time.sleep(1)
        logger.info("sleep 5 seconds ...")
        download_file = 'Y'
        messages.info(request, 'File successfully created.')

        user_filter = UserFilter(request.POST, queryset=user_list)
    if request.method == 'GET':
        user_filter = UserFilter(request.GET, queryset=user_list)

    return render(request, 'myApp/user_list.html', {'filter': user_filter, "download_file": download_file})


def search_car(request):
    car_list = Car.objects.all()
    if request.method == 'POST':
        car_filter = CarListingFilter(request.POST, queryset=car_list)
    if request.method == 'GET':
        car_filter = CarListingFilter(request.GET, queryset=car_list)

    return render(request, 'myApp/car_list.html', {'car_filter': car_filter})


def download_file(request):
    logger.info("downloading file ....")
    file_download = "django_web"

    zipper = os.path.join("c:/TEMP/logs", file_download + ".zip")

    resp = HttpResponse(open(zipper, 'rb').read(),
                        content_type="application/octet-stream")
    resp['Content-Disposition'] = 'attachment; filename=%s.zip' % file_download
    resp['Set-Cookie'] = 'fileDownload=true; Path=/'

    return resp


def group_user(request):
    users = User.objects.all()

    # group_users = []
    h_group_users = []
    q = ""

    # if request.method == 'GET' and 'q' in request.GET:
    #     q = request.GET["q"]
    if request.method == 'POST':
        print(f" POST {request.POST}")
        q = request.POST["q"]
        if q is not None and q != '':
            print(f"user filter {q}")
            users = users.filter(username__icontains=q)

        action = request.POST['form-action']
        h_group_users_str = request.POST['h-group-users']
        h_group_users = json.loads(h_group_users_str.replace("'", "\""))

        print(
            f" hidden group users {h_group_users_str}, --> {h_group_users}  {type(h_group_users)}")

        if action == 'ADD':
            user_selected = request.POST.getlist("user_selected")

            print(f"user selected {user_selected}")

            h_group_users.extend(user_selected)
            h_group_users.sort(key=str.lower)

        if action == 'REMOVE':
            group_selected = request.POST.getlist("group_selected")
            print(f"group selected {group_selected}")
            h_group_users = [
                x for x in h_group_users if x not in group_selected]

    users = users.exclude(username__in=h_group_users)
    user_list = [DropDownKeyValue(u.username, str(u)) for u in users]
    group_users = [DropDownKeyValue(u, u) for u in h_group_users]

    ctx = {"q": q, "search_q": q,  'h_group_users': h_group_users,
           'users': user_list,
           'group_users': group_users

           }

    # return render(request, 'myApp/group_user.html', ctx)
    return render(request, 'myApp/group_user_js.html', ctx)

MyWeb/templates/myApp/basic_contact.html
<!DOCTYPE html>
<html>
{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<head>
    <meta charset="utf-8">
    <title>Basic contact form</title>
</head>

<body>
    <div class="container w-100">
        <div class="col-6">
            <form method="post" class="form">
                <!--add attribute novalidate to by pass clientside validation -->
                {% csrf_token %}

                {% if form.field_errors %}
                <ul>
                    {% for error in form.field_errors %}
                    <li>form.field_errors : {{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}


                <div class="table-responsive">
                    <table border="1" class="table">
                        <tr>
                            <th>{{ form.name.label_tag }}</th>
                            <td>
                                {{ form.name.errors }}
                                {{ form.name }}
                                {{ form.name.help_text }}
                                {{ form.errors.name }}

                            </td>
                        </tr>

                        <tr>
                            <th>{{ form.email.label_tag }}</th>
                            <td>
                                {{ form.email.errors }}
                                {{ form.email }}
                                {{ form.errors.email }}
                            </td>
                        </tr>

                        <th>{{ form.password.label_tag }}</th>
                        <td>
                            {{ form.password }}
                        </td>
                        </tr>

                        <tr>
                            <th>{{ form.message.label_tag }}</th>
                            <td>
                                {{ form.message.errors }}
                                {{ form.message }}
                                <br />
   							    {% for err in form.message.errors %}
									<small class="text-danger ml-2">{{ err }}</small><br>
								{% endfor %}
                                {{ form.message.help_text }}
                            </td>
                        </tr>

                    </table>
                </div>

                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
        </div>
    </div>
</body>

</html>

MyWeb/templates/myApp/car_list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="d-flex align-items-center justify-content-center container">
    <div class="row">
        <div class="col-6">
            <h2>Auto dealer</h2>
            <p>
                The best place to find your car
            </p>
        </div>
        <div class="col-6">
            <form method="POST">
                {% csrf_token %}
                <table>
                    {{ car_filter.form |crispy }}
                </table>
                <button type="submit" class="btn btn-primary">
                    Search
                </button>
            </form>
        </div>
    </div>
</div>
<p class="text-center">-----------------------------------------------------</p>
<div class="d-flex align-items-center justify-content-center container">
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th>Brand</th>
                    <th>Transmission</th>
                    <th>Mileage</th>
                    <th>Color</th>
                    <th>Year</th>
                    <th>Price</th>
                    <th>Decription</th>
                </tr>
            </thead>
            <tbody>
                {% for u in car_filter.qs %}
                <tr>
                    <td>{{ u.brand }}</td>
                    <td>{{ u.trans_type }}</td>
                    <td>{{ u.mileage }}</td>
                    <td>{{ u.color }}</td>
                    <td>{{ u.year }}</td>
                    <td>{{ u.price }}</td>
                    <td>{{ u.description }}</td>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="5">No data</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</div>

{% endblock %}

MyWeb/templates/myApp/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

MyWeb/templates/myApp/dropdown.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %} Dynmaic drop down{% endblock %}

{% block content %}

{% csrf_token %}
<div class="col-md-6">
    <div class="form-group">
        <label for="inputStatus">Country</label>
        <select id="question-subject" class="form-control-sm custom-select">
            <option selected disabled>Choose a Country</option>
            {% for subject in subjects%}
            <option value="{{subject.key}}">{{subject.value}}</option>
            {% endfor %}
        </select>
    </div>
</div>
<div class="col-md-6">
    <div class="form-group">
        <label for="inputStatus">City</label>
        <select id="question-topic" class="form-control-sm custom-select" name="topic">
            <option selected disabled>Choose a City</option>
        </select>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
    crossorigin="anonymous"></script>
<script>
    $("#question-subject").change(function () {
        const subjectId = $(this).val();  // get the selected subject ID from the HTML dropdown list 
        $.ajax({                       // initialize an AJAX request
            type: "POST",
            url: '{% url "get_cities_ajax" %}',
            data: {
                'subject_id': subjectId,       // add the country id to the POST parameters
                'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
            },
            success: function (data) {   // `data` is from `get_topics_ajax` view function
                let html_data = '<option value="">---------</option>';
                data.forEach(function (data) {
                    html_data += `<option value="${data.key}">${data.value}</option>`
                });
                $("#question-topic").html(html_data); // replace the contents of the topic input with the data that came from the server
            }
        });
    });
</script>


{% endblock %}

MyWeb/templates/myApp/group_user.html
{% extends 'base.html' %}



{% load my_tags %}

{% block content %}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />


<form method="POST" id="changelist-form">
    <input type="hidden" name="form-action" id="changelist-form-action" value="">
    <input type="hidden" name="h-group-users" value="{{h_group_users}}">


    {% csrf_token %}

    <div class="d-flex flex-row justify-content-center m-4" style="width:60%">

        <div class="card col-5">
            <div class="card-body">
                <div class="row">
                    <div class="input-group m-1 p-1">
                        <span class="m-1 p-1">Users</span>
                        <input type="text" class="form-control" placeholder="Search..." name="q" value="{{ q }}">
                        <div class="input-group-append">
                            <button class="btn btn-secondary" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <select class="form-control select_field_class" multiple="multiple" size="5" name="user_selected">
                        {% for u in users%}
                        <option value="{{u.key}}">{{u.value}}</option>
                        {% endfor %}
                    </select>
                </div>

            </div>
        </div>
        <div class="align-self-center p-2" style="width:30px">

            <i class="bi bi-arrow-right-circle" type="submit" onclick="return on_add_click()">
            </i>
            <br>
            <i class="bi bi-arrow-left-circle" type="submit" onclick="return on_remove_click()">
            </i>
            <br>

        </div>

        <div class="card col-5">
            <div class="card-body">
                <div class="row m-2 p-1">Group :</div>

                <div class="row">
                    <select class="form-control select_field_class" multiple="multiple" size="5" name="group_selected">
                        {% for u in group_users %}
                        <option value="{{u.key}}">{{u.value}}</option>
                        {% endfor %}
                    </select>
                </div>

            </div>
        </div>
    </div>
</form>


<script type="text/javascript">

    function on_add_click() {
        var a = document.getElementById("changelist-form-action")
        a.value = "ADD"
        document.getElementById("changelist-form").submit();
    }

    function on_remove_click() {
        var a = document.getElementById("changelist-form-action")
        a.value = "REMOVE"
        document.getElementById("changelist-form").submit();
    }

</script>

{% endblock %}

MyWeb/templates/myApp/group_user_js.html
{% extends 'base.html' %}



{% load my_tags %}

{% block content %}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />


<form method="POST" id="changelist-form">
    <input type="hidden" name="form-action" id="changelist-form-action" value="">
    <input type="hidden" name="h-group-users" id="h-group-users-id" value="">
    <input type="hidden" name="h-users" id="h-users-id" value="">


    {% csrf_token %}

    <div class="d-flex flex-row justify-content-center m-4" style="width:60%">

        <div class="card col-5">
            <div class="card-body">
                <div class="row">
                    <div class="input-group m-1 p-1">
                        <span class="m-1 p-1">Users</span>
                        <input type="text" class="form-control" placeholder="Search..." name="q" value="{{ q }}"
                            id="myInput" onkeyup="filterFunction()">
                    </div>
                </div>
                <div class="row">
                    <select class="form-control select_field_class" multiple="multiple" size="5" name="user_selected"
                        id="user_selected_id">
                        {% for u in users%}
                        <option value="{{u.key}}">{{u.value}}</option>
                        {% endfor %}
                    </select>
                </div>

            </div>
        </div>
        <div class="align-self-center p-2" style="width:30px">

            <i class="bi bi-arrow-right-circle" type="submit" onclick="return on_add_click()">
            </i>
            <br>
            <i class="bi bi-arrow-left-circle" type="submit" onclick="return on_remove_click()">
            </i>
            <br>

        </div>

        <div class="card col-5">
            <div class="card-body">
                <div class="row m-2 p-1">Group :</div>

                <div class="row">
                    <select class="form-control select_field_class" multiple="multiple" size="5" name="group_selected"
                        id="group_selected_id" ">
                        {% for u in group_users %}
                        <option value=" {{u.key}}">{{u.value}}</option>
                        {% endfor %}
                    </select>
                </div>

            </div>
        </div>

        <div class="align-self-end p-2" style="width:100px">

            <button class="btn btn-primary" type="submit" onclick="return on_submit_click()">
                Save</button>
        </div>

    </div>
</form>


<script type="text/javascript">
    function on_submit_click() {
        var selected = [];
        for (var option of document.getElementById('group_selected_id').options) {
            selected.push(option.value);
        }
        alert(selected)
        return false;
    }


    function filterFunction() {
        var input, filter, ul, li, a, i;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        div = document.getElementById("user_selected_id");
        a = div.getElementsByTagName("option");
        for (i = 0; i < a.length; i++) {
            txtValue = a[i].textContent || a[i].innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                a[i].style.display = "";
            } else {
                a[i].style.display = "none";
            }
        }
    }

    function on_add_click() {
        var a = document.getElementById("changelist-form-action");
        a.value = "ADD";

        var groupselect = document.getElementById("group_selected_id");

        var selectobject = document.getElementById("user_selected_id");

        for (var i = 0; i < selectobject.length; i++) {
            let option = selectobject.options[i];
            if (option.selected) {
                let s = option.value;
                let new_option = new Option(s, s);
                groupselect.add(new_option, undefined);
                selectobject.remove(i);
                i--;

            }
        }

        $("#user_selected_id").html($("#user_selected_id option").sort(function (a, b) {
            return a.text == b.text ? 0 : a.text.toLowerCase() < b.text.toLowerCase() ? -1 : 1
        }))

        $("#group_selected_id").html($("#group_selected_id option").sort(function (a, b) {
            return a.text == b.text ? 0 : a.text.toLowerCase() < b.text.toLowerCase() ? -1 : 1
        }))
    }

    function on_remove_click() {
        var a = document.getElementById("changelist-form-action")
        a.value = "REMOVE"

        var userselect = document.getElementById("user_selected_id");

        var selectobject = document.getElementById("group_selected_id");

        for (var i = 0; i < selectobject.length; i++) {
            let option = selectobject.options[i];
            if (option.selected) {
                let s = option.value;
                let new_option = new Option(s, s);
                userselect.add(new_option, undefined);
                selectobject.remove(i);
                i--;

            }
        }

        // resort the dropdown
        $("#user_selected_id").html($("#user_selected_id option").sort(function (a, b) {
            return a.text == b.text ? 0 : a.text.toLowerCase() < b.text.toLowerCase() ? -1 : 1
        }))

        $("#group_selected_id").html($("#group_selected_id option").sort(function (a, b) {
            return a.text == b.text ? 0 : a.text.toLowerCase() < b.text.toLowerCase() ? -1 : 1
        }))
    }

</script>

{% endblock %}

MyWeb/templates/myApp/person_form.html
{% extends 'base.html' %}


{% block content %}

<h2>Person Form</h2>

<form method="post" id="personForm" data-cities-url="{% url 'ajax_load_cities' %}" novalidate>
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit">Save</button>
  <a href="{% url 'person_changelist' %}">Nevermind</a>
</form>

<!--
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
-->


<script>
  $("#id_country").change(function () {
    var url = $("#personForm").attr("data-cities-url");
    var countryId = $(this).val();

    $.ajax({
      url: url,
      data: {
        'countryId': countryId
      },
      success: function (data) {
        $("#id_city").html(data);
      }
    });

  });
</script>

{% endblock %}

MyWeb/templates/myApp/person_list.html
{% extends 'base.html' %}

{% block title %}Human Resources Module{% endblock %}

{% block content %}
<div class="container-fluid">
  <h2 class="center">Human Resources Module » People Management</h2>

  <p>
    <a href="{% url 'person_add' %}">Add person</a>
  </p>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Birthdate</th>
        <th>Country</th>
        <th>City</th>
      </tr>
    </thead>
    <tbody>
      {% for person in people %}
      <tr>
        <td><a href="{% url 'person_change' person.pk %}">{{ person.name }}</a></td>
        <td>{{ person.birthdate }}</td>
        <td>{{ person.country.name }}</td>
        <td>{{ person.city.name }}</td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="4">No person in the database. <a href="{% url 'person_add' %}">Add the first person</a>.</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}