MyWeb/MyWeb/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic.base import TemplateView

handler404 = "corm.views.NotFound.error_404"

urlpatterns = [
    path("admin/", admin.site.urls),
    path('myApp/', include('myApp.urls')),
    path('corm/', include('corm.urls')),
    path('gplot/', include('gplot.urls')),
    path('mychart/', include('mychart.urls')),
    path('myDatable/', include('myDatable.urls')),
    path('api/', include('api.urls')),

    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

MyWeb/api/urls.py
from django.urls import include, path

from .views import MyTokenObtainPairView, getUserAccess, chatroom

from rest_framework_simplejwt.views import (
    TokenRefreshView,
)

urlpatterns = [
    path("token/", MyTokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("useraccess/", getUserAccess, name="getUserAccess"),
    path("chatroom/<str:room_name>/", chatroom, name="chatroom"),
]

MyWeb/myDatable/urls.py
# urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='dt-show'),
    path('addnew', views.addnew, name='dt-addnew'),
    path('edit/<int:id>', views.edit,  name='dt-edit'),
    path('update/<int:id>', views.update, name='dt-update'),
    path('delete/<int:id>', views.destroy, name='dt-delete'),
]

MyWeb/myDatable/models.py
from django.db import models


class Employee(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    contact = models.CharField(max_length=15)

    class Meta:
        db_table = "employee"

MyWeb/myDatable/forms.py
from django import forms
from .models import Employee


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        # https://docs.djangoproject.com/en/3.0/ref/forms/widgets/
        fields = ['name', 'contact', 'email']
        widgets = {'name': forms.TextInput(attrs={'class': 'form-control'}),
                   'email': forms.EmailInput(attrs={'class': 'form-control'}),
                   'contact': forms.TextInput(attrs={'class': 'form-control'}),
                   }

MyWeb/myDatable/views.py
from django.shortcuts import render

from django.shortcuts import render, redirect
from .forms import EmployeeForm
from .models import Employee
# Create your views here.


def addnew(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        print(f"insert new emplyee {form}")
        if form.is_valid():
            try:
                form.save()
                return redirect('dt-show')
            except:
                pass
    else:
        form = EmployeeForm()
    return render(request, 'myDatable/add.html', {'form': form})


def index(request):
    employees = Employee.objects.all().order_by('-id')
    form = EmployeeForm()
    return render(request, "myDatable/show.html", {'employees': employees,  'form': form})


def edit(request, id):
    employee = Employee.objects.get(id=id)
    return render(request, 'myDatable/edit.html', {'employee': employee})


def update(request, id):
    
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST, instance=employee)

    print(f"update emplyee {form}")
    if form.is_valid():
        form.save()
        return redirect('dt-show')
    return render(request, 'myDatable/edit.html', {'employee': employee})


def destroy(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect('dt-show')

MyWeb/templates/myDatable/add.html
<!-- ADD Modal -->
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addModalLabel">
                    <i class="fas fa-plus"></i> Add Employee
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <!-- Modal content-->
            <div class="modal-body">

                {% block content %}

                <form method="POST" class="post-form" action="{% url 'dt-addnew' %}">
                    {% csrf_token %}
                    <div class="container">
                        <br>
                        <div class="form-group row">
                            <label class="col-sm-1 col-form-label"></label>
                            <div>
                                <h3>Enter Details</h3>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Employee Name:</label>
                            <div class="col-sm-8">
                                {{ form.name }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Employee Email:</label>
                            <div class="col-sm-8">
                                {{ form.email }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Employee Contact:</label>
                            <div class="col-sm-8">
                                {{ form.contact }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-1 col-form-label"></label>
                            <div class="col-sm-4">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </div>
                </form>

                {% endblock content %}
            </div>
            <!-- END Modal content-->



            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

MyWeb/templates/myDatable/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}

    {% load bootstrap4 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
        crossorigin="anonymous">

    <link
        href="https://cdn.datatables.net/v/bs4/dt-1.13.4/b-2.3.6/b-colvis-2.3.6/b-html5-2.3.6/b-print-2.3.6/datatables.min.css"
        rel="stylesheet" />

    <script
        src="https://cdn.datatables.net/v/bs4/dt-1.13.4/b-2.3.6/b-colvis-2.3.6/b-html5-2.3.6/b-print-2.3.6/datatables.min.js"></script>


</head>

<body>
    <div class="container">
        <div class="row">
            {% block content %}{% endblock %}
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $('#bootstrapdatatable').DataTable({
                lengthMenu: [[3, 5, 10, -1], [3, 5, 10, "All"]],

                columnDefs: [
                    { orderable: false, targets: [0, -1, -2] }
                ]

            }
            );
        });
    </script>
</body>

</html>

MyWeb/templates/myDatable/edit.html
<!-- ADD Modal -->
<div class="modal fade" id="editModal{{ employee.id }}" tabindex="-1" role="dialog" aria-labelledby="editModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addModalLabel">
                    <i class="fas fa-plus"></i> Edit Employee
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <!-- Modal content-->
            <div class="modal-body">


                <div class="col-md-12">
                    <form method="POST" class="post-form" action="{% url 'dt-update' employee.id %}">
                        {% csrf_token %}
                        <div class="container">
                            <br>
                            <div class="form-group row">
                                <label class="col-sm-1 col-form-label"></label>
                                <div class="col-sm-4">
                                    <h3>Update Details</h3>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-4 col-form-label">Employee Id:</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" name="id" id="id_id" required maxlength="20"
                                        value="{{ employee.id }}" />
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-4 col-form-label">Employee Name:</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" name="name" id="id_name" required
                                        maxlength="100" value="{{ employee.name }}" />
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-4 col-form-label">Employee Email:</label>
                                <div class="col-sm-8">
                                    <input type="email" class="form-control" name="email" id="id_email" required
                                        maxlength="254" value="{{ employee.email }}" />
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-4 col-form-label">Employee Contact:</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" name="contact" id="id_contact" required
                                        maxlength="15" value="{{ employee.contact }}" />
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-1 col-form-label"></label>
                                <div class="col-sm-4">
                                    <button type="submit" class="btn btn-success btn-lg">Update</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>


            <!-- END Modal content-->



            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

MyWeb/templates/myDatable/show.html
{% extends "myDatable/base.html" %}

{% block title %}Employee Records{% endblock title %}

{% block content %}
<div class="col-md-12">
    <h4>Django CRUD (Create Read Update Delete) Example - Bootstrap Datatable</h4>

    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#addModal">
        <i class="fa-solid fa-user-plus"></i>
    </button>


    <div class="table-responsive">
        <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
            <thead>

                <th>ID</th>
                <th>Employee Name</th>
                <th>Employee Email</th>
                <th>Employee Contact</th>
                <th>Edit</th>
                <th>Delete</th>
            </thead>
            <tbody>
                {% for employee in employees %}
                <tr>

                    <td>{{ employee.id }}</td>
                    <td>{{ employee.name }}</td>
                    <td>{{ employee.email }}</td>
                    <td>{{ employee.contact }}</td>
                    <td>

                        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal"
                            data-target="#editModal{{ employee.id }}">
                            <i class="fas fa-user-edit">Edit</i>
                        </button>
                    </td>
                    <td>
                        <p data-placement="top" data-toggle="tooltip" title="Delete"><a
                                href="{% url 'dt-delete' employee.id %}" class="btn btn-danger btn-xs"
                                data-title="Delete" data-toggle="modal" data-target="#delete"><i
                                    class="fa fa-trash"></i></a></p>
                    </td>
                </tr>

                {% include 'myDatable/edit.html' %}

                {% endfor %}
            </tbody>

        </table>
    </div>
</div>
{% include 'myDatable/add.html' %}

{% endblock content %}